package de.hysky.skyblocker.skyblock.item;

import de.hysky.skyblocker.utils.NEURepoManager;
import io.github.moulberry.repo.NEUItems;
import io.github.moulberry.repo.data.NEUItem;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

class PetTest {

    @Test
    void testFromItemId() {
        NEUItems neuItems = NEURepoManager.NEU_REPO.getItems();
        try {
            Field items = NEUItems.class.getDeclaredField("items");
            items.setAccessible(true);
            HashMap<String, NEUItem> map = new HashMap<>();
            map.put("ENDERMAN;0", new NEUItem());
            map.put("ENDERMAN;1", new NEUItem());
            map.put("ENDERMAN;2", new NEUItem());
            map.put("ENDERMAN;3", new NEUItem());
            map.put("ENDERMAN;4", new NEUItem());
            map.put("ENDERMAN;5", new NEUItem());
            items.set(neuItems, map);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
        Assertions.assertEquals(new Pet("ENDERMAN", SkyblockItemRarity.COMMON, 0), Pet.fromItemId("ENDERMAN;0"));
        Assertions.assertEquals(new Pet("ENDERMAN", SkyblockItemRarity.UNCOMMON, 0), Pet.fromItemId("ENDERMAN;1"));
        Assertions.assertEquals(new Pet("ENDERMAN", SkyblockItemRarity.RARE, 0), Pet.fromItemId("ENDERMAN;2"));
        Assertions.assertEquals(new Pet("ENDERMAN", SkyblockItemRarity.EPIC, 0), Pet.fromItemId("ENDERMAN;3"));
        Assertions.assertEquals(new Pet("ENDERMAN", SkyblockItemRarity.LEGENDARY, 0), Pet.fromItemId("ENDERMAN;4"));
        Assertions.assertEquals(new Pet("ENDERMAN", SkyblockItemRarity.MYTHIC, 0), Pet.fromItemId("ENDERMAN;5"));
        Assertions.assertEquals("ENDERMAN", Pet.fromItemId("ENDERMAN").getPetId());
        Assertions.assertThrows(RuntimeException.class, () -> Pet.fromItemId("ENDERM", -1));
        Assertions.assertThrows(RuntimeException.class, () -> Pet.fromItemId(null));
        Assertions.assertThrows(RuntimeException.class, () -> Pet.fromItemId("ENDERM"));
        Assertions.assertThrows(RuntimeException.class, () -> Pet.fromItemId("ENDERM;4"));
        Assertions.assertThrows(RuntimeException.class, () -> Pet.fromItemId("ENDERMAN;233"));
    }

    @Test
    void testGetPetLevel() {
        // test data generated from https://wiki.hypixel.net/Pets
        initPets();
        Pet pet = new Pet("ENDERMAN", SkyblockItemRarity.COMMON, 0);
        Assertions.assertEquals(1, pet.getPetLevel());
        pet.setPetExp(1340);
        Assertions.assertEquals(10, pet.getPetLevel());
        pet.setPetExp(89285);
        Assertions.assertEquals(50, pet.getPetLevel());
        pet.setPetExp(5624785);
        Assertions.assertEquals(100, pet.getPetLevel());
        pet.setPetExp(10000000);
        Assertions.assertEquals(100, pet.getPetLevel());
        pet = new Pet("ENDERMAN", SkyblockItemRarity.LEGENDARY, 0);
        Assertions.assertEquals(1, pet.getPetLevel());
        pet.setPetExp(2050430);
        Assertions.assertEquals(66, pet.getPetLevel());
        pet.setPetExp(25353230);
        Assertions.assertEquals(100, pet.getPetLevel());
        pet.setPetExp(30000000);
        Assertions.assertEquals(100, pet.getPetLevel());
        pet = new Pet("BINGO", SkyblockItemRarity.UNCOMMON, 0);
        Assertions.assertEquals(1, pet.getPetLevel());
        pet.setPetExp(1340);
        Assertions.assertEquals(10, pet.getPetLevel());
        pet.setPetExp(5624785);
        Assertions.assertEquals(100, pet.getPetLevel());
        pet.setPetExp(10000000);
        Assertions.assertEquals(100, pet.getPetLevel());
        pet = new Pet("GOLDEN_DRAGON", SkyblockItemRarity.LEGENDARY, 0);
        Assertions.assertEquals(1, pet.getPetLevel());
        pet.setPetExp(2050430);
        Assertions.assertEquals(66, pet.getPetLevel());
        pet.setPetExp(25353230);
        Assertions.assertEquals(101, pet.getPetLevel());
        pet.setPetExp(59319385);
        Assertions.assertEquals(120, pet.getPetLevel());
        pet.setPetExp(210255385);
        Assertions.assertEquals(200, pet.getPetLevel());
    }

    @Test
    void testSetPetLevel() {
        initPets();
        Pet pet = new Pet("ENDERMAN", SkyblockItemRarity.COMMON, 0);
        pet.setPetLevel(1);
        Assertions.assertEquals(0L, pet.getPetExp());
        pet.setPetLevel(10);
        Assertions.assertEquals(1340L, pet.getPetExp());
        pet.setPetLevel(50);
        Assertions.assertEquals(89285L, pet.getPetExp());
        pet.setPetLevel(100);
        Assertions.assertEquals(5624785L, pet.getPetExp());
        pet.setPetLevel(101);
        Assertions.assertEquals(5624785L, pet.getPetExp());
        pet = new Pet("ENDERMAN", SkyblockItemRarity.LEGENDARY, 0);
        pet.setPetLevel(1);
        Assertions.assertEquals(0L, pet.getPetExp());
        pet.setPetLevel(66);
        Assertions.assertEquals(2050430L, pet.getPetExp());
        pet.setPetLevel(100);
        Assertions.assertEquals(25353230L, pet.getPetExp());
        pet.setPetLevel(101);
        Assertions.assertEquals(25353230L, pet.getPetExp());
        pet = new Pet("BINGO", SkyblockItemRarity.UNCOMMON, 0);
        pet.setPetLevel(1);
        Assertions.assertEquals(0L, pet.getPetExp());
        pet.setPetLevel(10);
        Assertions.assertEquals(1340L, pet.getPetExp());
        pet.setPetLevel(50);
        Assertions.assertEquals(89285L, pet.getPetExp());
        pet.setPetLevel(100);
        Assertions.assertEquals(5624785L, pet.getPetExp());
        pet.setPetLevel(101);
        Assertions.assertEquals(5624785L, pet.getPetExp());
        pet = new Pet("GOLDEN_DRAGON", SkyblockItemRarity.LEGENDARY, 0);
        pet.setPetLevel(1);
        Assertions.assertEquals(0L, pet.getPetExp());
        pet.setPetLevel(66);
        Assertions.assertEquals(2050430L, pet.getPetExp());
        pet.setPetLevel(101);
        Assertions.assertEquals(25353230L, pet.getPetExp());
        pet.setPetLevel(120);
        Assertions.assertEquals(59319385L, pet.getPetExp());
        pet.setPetLevel(200);
        Assertions.assertEquals(210255385L, pet.getPetExp());
    }

    void initPets() {
        Pet.levelStartOffset.put(SkyblockItemRarity.COMMON, 0);
        Pet.levelStartOffset.put(SkyblockItemRarity.UNCOMMON, 6);
        Pet.levelStartOffset.put(SkyblockItemRarity.RARE, 11);
        Pet.levelStartOffset.put(SkyblockItemRarity.EPIC, 16);
        Pet.levelStartOffset.put(SkyblockItemRarity.LEGENDARY, 20);
        Pet.levelStartOffset.put(SkyblockItemRarity.MYTHIC, 20);
        Pet.petExpCostForLevel.add(100);
        Pet.petExpCostForLevel.add(110);
        Pet.petExpCostForLevel.add(120);
        Pet.petExpCostForLevel.add(130);
        Pet.petExpCostForLevel.add(145);
        Pet.petExpCostForLevel.add(160);
        Pet.petExpCostForLevel.add(175);
        Pet.petExpCostForLevel.add(190);
        Pet.petExpCostForLevel.add(210);
        Pet.petExpCostForLevel.add(230);
        Pet.petExpCostForLevel.add(250);
        Pet.petExpCostForLevel.add(275);
        Pet.petExpCostForLevel.add(300);
        Pet.petExpCostForLevel.add(330);
        Pet.petExpCostForLevel.add(360);
        Pet.petExpCostForLevel.add(400);
        Pet.petExpCostForLevel.add(440);
        Pet.petExpCostForLevel.add(490);
        Pet.petExpCostForLevel.add(540);
        Pet.petExpCostForLevel.add(600);
        Pet.petExpCostForLevel.add(660);
        Pet.petExpCostForLevel.add(730);
        Pet.petExpCostForLevel.add(800);
        Pet.petExpCostForLevel.add(880);
        Pet.petExpCostForLevel.add(960);
        Pet.petExpCostForLevel.add(1050);
        Pet.petExpCostForLevel.add(1150);
        Pet.petExpCostForLevel.add(1260);
        Pet.petExpCostForLevel.add(1380);
        Pet.petExpCostForLevel.add(1510);
        Pet.petExpCostForLevel.add(1650);
        Pet.petExpCostForLevel.add(1800);
        Pet.petExpCostForLevel.add(1960);
        Pet.petExpCostForLevel.add(2130);
        Pet.petExpCostForLevel.add(2310);
        Pet.petExpCostForLevel.add(2500);
        Pet.petExpCostForLevel.add(2700);
        Pet.petExpCostForLevel.add(2920);
        Pet.petExpCostForLevel.add(3160);
        Pet.petExpCostForLevel.add(3420);
        Pet.petExpCostForLevel.add(3700);
        Pet.petExpCostForLevel.add(4000);
        Pet.petExpCostForLevel.add(4350);
        Pet.petExpCostForLevel.add(4750);
        Pet.petExpCostForLevel.add(5200);
        Pet.petExpCostForLevel.add(5700);
        Pet.petExpCostForLevel.add(6300);
        Pet.petExpCostForLevel.add(7000);
        Pet.petExpCostForLevel.add(7800);
        Pet.petExpCostForLevel.add(8700);
        Pet.petExpCostForLevel.add(9700);
        Pet.petExpCostForLevel.add(10800);
        Pet.petExpCostForLevel.add(12000);
        Pet.petExpCostForLevel.add(13300);
        Pet.petExpCostForLevel.add(14700);
        Pet.petExpCostForLevel.add(16200);
        Pet.petExpCostForLevel.add(17800);
        Pet.petExpCostForLevel.add(19500);
        Pet.petExpCostForLevel.add(21300);
        Pet.petExpCostForLevel.add(23200);
        Pet.petExpCostForLevel.add(25200);
        Pet.petExpCostForLevel.add(27400);
        Pet.petExpCostForLevel.add(29800);
        Pet.petExpCostForLevel.add(32400);
        Pet.petExpCostForLevel.add(35200);
        Pet.petExpCostForLevel.add(38200);
        Pet.petExpCostForLevel.add(41400);
        Pet.petExpCostForLevel.add(44800);
        Pet.petExpCostForLevel.add(48400);
        Pet.petExpCostForLevel.add(52200);
        Pet.petExpCostForLevel.add(56200);
        Pet.petExpCostForLevel.add(60400);
        Pet.petExpCostForLevel.add(64800);
        Pet.petExpCostForLevel.add(69400);
        Pet.petExpCostForLevel.add(74200);
        Pet.petExpCostForLevel.add(79200);
        Pet.petExpCostForLevel.add(84700);
        Pet.petExpCostForLevel.add(90700);
        Pet.petExpCostForLevel.add(97200);
        Pet.petExpCostForLevel.add(104200);
        Pet.petExpCostForLevel.add(111700);
        Pet.petExpCostForLevel.add(119700);
        Pet.petExpCostForLevel.add(128200);
        Pet.petExpCostForLevel.add(137200);
        Pet.petExpCostForLevel.add(146700);
        Pet.petExpCostForLevel.add(156700);
        Pet.petExpCostForLevel.add(167700);
        Pet.petExpCostForLevel.add(179700);
        Pet.petExpCostForLevel.add(192700);
        Pet.petExpCostForLevel.add(206700);
        Pet.petExpCostForLevel.add(221700);
        Pet.petExpCostForLevel.add(237700);
        Pet.petExpCostForLevel.add(254700);
        Pet.petExpCostForLevel.add(272700);
        Pet.petExpCostForLevel.add(291700);
        Pet.petExpCostForLevel.add(311700);
        Pet.petExpCostForLevel.add(333700);
        Pet.petExpCostForLevel.add(357700);
        Pet.petExpCostForLevel.add(383700);
        Pet.petExpCostForLevel.add(411700);
        Pet.petExpCostForLevel.add(441700);
        Pet.petExpCostForLevel.add(476700);
        Pet.petExpCostForLevel.add(516700);
        Pet.petExpCostForLevel.add(561700);
        Pet.petExpCostForLevel.add(611700);
        Pet.petExpCostForLevel.add(666700);
        Pet.petExpCostForLevel.add(726700);
        Pet.petExpCostForLevel.add(791700);
        Pet.petExpCostForLevel.add(861700);
        Pet.petExpCostForLevel.add(936700);
        Pet.petExpCostForLevel.add(1016700);
        Pet.petExpCostForLevel.add(1101700);
        Pet.petExpCostForLevel.add(1191700);
        Pet.petExpCostForLevel.add(1286700);
        Pet.petExpCostForLevel.add(1386700);
        Pet.petExpCostForLevel.add(1496700);
        Pet.petExpCostForLevel.add(1616700);
        Pet.petExpCostForLevel.add(1746700);
        Pet.petExpCostForLevel.add(1886700);
        List<Integer> gdPetExpCostForLevel = new ArrayList<>();
        gdPetExpCostForLevel.add(100);
        gdPetExpCostForLevel.add(110);
        gdPetExpCostForLevel.add(120);
        gdPetExpCostForLevel.add(130);
        gdPetExpCostForLevel.add(145);
        gdPetExpCostForLevel.add(160);
        gdPetExpCostForLevel.add(175);
        gdPetExpCostForLevel.add(190);
        gdPetExpCostForLevel.add(210);
        gdPetExpCostForLevel.add(230);
        gdPetExpCostForLevel.add(250);
        gdPetExpCostForLevel.add(275);
        gdPetExpCostForLevel.add(300);
        gdPetExpCostForLevel.add(330);
        gdPetExpCostForLevel.add(360);
        gdPetExpCostForLevel.add(400);
        gdPetExpCostForLevel.add(440);
        gdPetExpCostForLevel.add(490);
        gdPetExpCostForLevel.add(540);
        gdPetExpCostForLevel.add(600);
        gdPetExpCostForLevel.add(660);
        gdPetExpCostForLevel.add(730);
        gdPetExpCostForLevel.add(800);
        gdPetExpCostForLevel.add(880);
        gdPetExpCostForLevel.add(960);
        gdPetExpCostForLevel.add(1050);
        gdPetExpCostForLevel.add(1150);
        gdPetExpCostForLevel.add(1260);
        gdPetExpCostForLevel.add(1380);
        gdPetExpCostForLevel.add(1510);
        gdPetExpCostForLevel.add(1650);
        gdPetExpCostForLevel.add(1800);
        gdPetExpCostForLevel.add(1960);
        gdPetExpCostForLevel.add(2130);
        gdPetExpCostForLevel.add(2310);
        gdPetExpCostForLevel.add(2500);
        gdPetExpCostForLevel.add(2700);
        gdPetExpCostForLevel.add(2920);
        gdPetExpCostForLevel.add(3160);
        gdPetExpCostForLevel.add(3420);
        gdPetExpCostForLevel.add(3700);
        gdPetExpCostForLevel.add(4000);
        gdPetExpCostForLevel.add(4350);
        gdPetExpCostForLevel.add(4750);
        gdPetExpCostForLevel.add(5200);
        gdPetExpCostForLevel.add(5700);
        gdPetExpCostForLevel.add(6300);
        gdPetExpCostForLevel.add(7000);
        gdPetExpCostForLevel.add(7800);
        gdPetExpCostForLevel.add(8700);
        gdPetExpCostForLevel.add(9700);
        gdPetExpCostForLevel.add(10800);
        gdPetExpCostForLevel.add(12000);
        gdPetExpCostForLevel.add(13300);
        gdPetExpCostForLevel.add(14700);
        gdPetExpCostForLevel.add(16200);
        gdPetExpCostForLevel.add(17800);
        gdPetExpCostForLevel.add(19500);
        gdPetExpCostForLevel.add(21300);
        gdPetExpCostForLevel.add(23200);
        gdPetExpCostForLevel.add(25200);
        gdPetExpCostForLevel.add(27400);
        gdPetExpCostForLevel.add(29800);
        gdPetExpCostForLevel.add(32400);
        gdPetExpCostForLevel.add(35200);
        gdPetExpCostForLevel.add(38200);
        gdPetExpCostForLevel.add(41400);
        gdPetExpCostForLevel.add(44800);
        gdPetExpCostForLevel.add(48400);
        gdPetExpCostForLevel.add(52200);
        gdPetExpCostForLevel.add(56200);
        gdPetExpCostForLevel.add(60400);
        gdPetExpCostForLevel.add(64800);
        gdPetExpCostForLevel.add(69400);
        gdPetExpCostForLevel.add(74200);
        gdPetExpCostForLevel.add(79200);
        gdPetExpCostForLevel.add(84700);
        gdPetExpCostForLevel.add(90700);
        gdPetExpCostForLevel.add(97200);
        gdPetExpCostForLevel.add(104200);
        gdPetExpCostForLevel.add(111700);
        gdPetExpCostForLevel.add(119700);
        gdPetExpCostForLevel.add(128200);
        gdPetExpCostForLevel.add(137200);
        gdPetExpCostForLevel.add(146700);
        gdPetExpCostForLevel.add(156700);
        gdPetExpCostForLevel.add(167700);
        gdPetExpCostForLevel.add(179700);
        gdPetExpCostForLevel.add(192700);
        gdPetExpCostForLevel.add(206700);
        gdPetExpCostForLevel.add(221700);
        gdPetExpCostForLevel.add(237700);
        gdPetExpCostForLevel.add(254700);
        gdPetExpCostForLevel.add(272700);
        gdPetExpCostForLevel.add(291700);
        gdPetExpCostForLevel.add(311700);
        gdPetExpCostForLevel.add(333700);
        gdPetExpCostForLevel.add(357700);
        gdPetExpCostForLevel.add(383700);
        gdPetExpCostForLevel.add(411700);
        gdPetExpCostForLevel.add(441700);
        gdPetExpCostForLevel.add(476700);
        gdPetExpCostForLevel.add(516700);
        gdPetExpCostForLevel.add(561700);
        gdPetExpCostForLevel.add(611700);
        gdPetExpCostForLevel.add(666700);
        gdPetExpCostForLevel.add(726700);
        gdPetExpCostForLevel.add(791700);
        gdPetExpCostForLevel.add(861700);
        gdPetExpCostForLevel.add(936700);
        gdPetExpCostForLevel.add(1016700);
        gdPetExpCostForLevel.add(1101700);
        gdPetExpCostForLevel.add(1191700);
        gdPetExpCostForLevel.add(1286700);
        gdPetExpCostForLevel.add(1386700);
        gdPetExpCostForLevel.add(1496700);
        gdPetExpCostForLevel.add(1616700);
        gdPetExpCostForLevel.add(1746700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(0);
        gdPetExpCostForLevel.add(5555);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        gdPetExpCostForLevel.add(1886700);
        Pet.customPetLeveling.put("GOLDEN_DRAGON", new Pet.CustomPetLeveling(1, Pet.levelStartOffset, 200, gdPetExpCostForLevel));
        Map<SkyblockItemRarity, Integer> bingoLevelStartOffset = new HashMap<>();
        bingoLevelStartOffset.put(SkyblockItemRarity.COMMON, 0);
        bingoLevelStartOffset.put(SkyblockItemRarity.UNCOMMON, 0);
        bingoLevelStartOffset.put(SkyblockItemRarity.RARE, 0);
        bingoLevelStartOffset.put(SkyblockItemRarity.EPIC, 0);
        bingoLevelStartOffset.put(SkyblockItemRarity.LEGENDARY, 0);
        Pet.customPetLeveling.put("BINGO", new Pet.CustomPetLeveling(1, bingoLevelStartOffset, 100, Pet.petExpCostForLevel));
        Pet.customPetLeveling.put("REINDEER", new Pet.CustomPetLeveling(2, Pet.levelStartOffset, 100, Pet.petExpCostForLevel));

    }
}